---

- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: "Install mysql-server 8.0 package"
  ansible.builtin.apt:
    name:
      - "mysql-server-8.0"
      - mc
      - nano
    state: "present"
