---

- name: "Install Debian-based"
  ansible.builtin.include_tasks: install.yml
  tags: install
  when: ansible_os_family not in ['RedHat', 'Rocky']

- name: "Install Red hat based"
  ansible.builtin.include_tasks: install-centos.yml
  tags: install
  when: ansible_os_family in ['RedHat', 'Rocky']
